version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.3.1
    ports:
      - "4444:4444"
    networks:
      - e2e
  chrome:
    image: selenium/node-chrome:3.3.1
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
    volumes:
      - /dev/shm:/dev/shm
      - ${PWD}:/wp-e2e-tests:ro
    links:
      - "wp-calypso:wpcalypso.wordpress.com"
    networks:
      - e2e
  wp-calypso:
    image: wp-calypso
    user: root
    environment:
      - PORT=80
      - NODE_ENV=production
      - CALYPSO_ENV=wpcalypso
    networks:
      - e2e
networks:
  e2e:
