version: "3"
services:
  mysql:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: super_secret_secure_password
  wordpress:
    image: wp-jetpack
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_PASSWORD: super_secret_secure_password
